version: '2'
services:
  registry:
    image: registry:2.6.2
    environment:
      REGISTRY_LOG_LEVEL: warn
      REGISTRY_NOTIFICATIONS_ENDPOINTS: |-
        - name: portus
          url: http://portus:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_REALM: https://${DOMAIN}:50010/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${DOMAIN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${DOMAIN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/registry.crt
    stdin_open: true
    volumes:
    - /etc/certs:/certs
    - /${DIR}/RegistryData:/var/lib/registry
    tty: true
    links:
    - portusMain:portus
    - PortusBackground:pback
  lb:
    image: rancher/lb-service-haproxy:v0.9.6
    stdin_open: true
    tty: true
    ports:
    - 50011:50011/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
  db:
    image: library/mariadb:10.0.23
    environment:
      MYSQL_DATABASE: portus
      MYSQL_PASSWORD: ${DBPASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOTPASSWORD}
      MYSQL_USER: portus
    stdin_open: true
    tty: true
    command:
    - mysqld
    - --character-set-server=utf8
    - --collation-server=utf8_unicode_ci
    - --init-connect=SET NAMES UTF8;
    - --innodb-flush-log-at-trx-commit=0
    labels:
      registry.portus.db: '1'
    volumes:
    - /${DIR}/mysql/:/var/lib/mysql
  portusMain:
    image: opensuse/portus:head
    environment:
      PORTUS_CHECK_SSL_USAGE_ENABLED: 'true'
      PORTUS_GRAVATAR_ENABLED: 'true'
      PORTUS_KEY_PATH: /certs/registry.key
      PORTUS_MACHINE_FQDN_VALUE: ${DOMAIN}
      PORTUS_PASSWORD: ${ROOTPASSWORD}
      PORTUS_SECRET_KEY_BASE: ${ROOTPASSWORD}
      PORTUS_SMTP_ENABLED: 'false'
      CCONFIG_PREFIX: PORTUS
      PORTUS_DB_HOST: db
      PORTUS_DB_PASSWORD: ${DBPASSWORD}
      PORTUS_DB_POOL: '5'
      RAILS_SERVE_STATIC_FILES: 'true'
      PORTUS_PUMA_HOST: 0.0.0.0:3000
      PORTUS_DB_USERNAME: portus
      PORTUS_DB_DATABASE: portus
    stdin_open: true
    volumes:
    - /etc/certs:/certs
    - ${DIR}:/srv/Portus
    tty: true
    links:
    - db:db
    - PortusBackground:PortusBackground
    - registry:registry
    command:
    - bundle
    - exec
    - rails
    - runner
    - /srv/Portus/examples/development/compose/init.rb
    labels:
      registry.portus.app: '1'
      io.rancher.scheduler.affinity:container_label_soft: registry.portus.db=1
      io.rancher.container.pull_image: always
  PortusBackground:
    image: opensuse/portus:head
    environment:
      PORTUS_MACHINE_FQDN_VALUE: ${DOMAIN}
      PORTUS_DB_HOST: db
      PORTUS_DB_PASSWORD: ${DBPASSWORD}
      PORTUS_DB_POOL: '5'
      PORTUS_CHECK_SSL_USAGE_ENABLED: 'false'
      PORTUS_SECRET_KEY_BASE: ${ROOTPASSWORD}
      PORTUS_BACKGROUND: 'true'
      PORTUS_KEY_PATH: /certs/registry.key
      PORTUS_PASSWORD: ${ROOTPASSWORD}
      PORTUS_GRAVATAR_ENABLED: 'true'
      PORTUS_SMTP_ENABLED: 'false'
      CCONFIG_PREFIX: PORTUS
      PORTUS_DB_USERNAME: portus
      PORTUS_DB_DATABASE: portus
    stdin_open: true
    volumes:
    - ${DIR}:/srv/Portus
    - /etc/certs:/certs
    tty: true
    links:
    - db:db
    - portusMain:portusMain
    - registry:registry
    command:
    - bundle
    - exec
    - rails
    - runner
    - /srv/Portus/bin/background.rb
    labels:
      io.rancher.container.pull_image: always
