version: '2'
catalog:
  name: "Registry"
  version: "0.50.2"
  description: "Complete Home Automation System"
services:
  registry:
    scale: 1
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      default_cert: wildcard.sdc.t-systems.com
      port_rules:
      - priority: 1
        protocol: https
        service: registry
        source_port: 443
        target_port: 5000
      - priority: 2
        protocol: https
        service: portusMain
        source_port: 50010
        target_port: 3000
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  db:
    scale: 1
    start_on_create: true
  portusMain:
    scale: 1
    start_on_create: true
  PortusBackground:
    scale: 1
    start_on_create: true
