version: '2'
catalog:
  name: "Registry"
  version: "1.0"
  description: "Registry wiht powerfull UI"
  questions:
    - variable: "DBPASSWORD"
      label: "DB Password"
      description: "Password for Portus database access, must be 8 characters or longer"
      required: true
      default: password
      type: "password"
    - variable: "ROOTPASSWORD"
      label: "DB Root Password"
      description: "Root Password for MariDB database, must be 8 characters or longer.  This is not normally used."
      required: true
      default: password
      type: "password"
    - variable: "DIR"
      label: "Certificate directory"
      description: "Path to certificates."
      required: true
      type: "string"
    - variable: "VNAME"
      label: "Name of the Registrystorage"
      description: "Name for shared storage to use for registry, database"
      required: true
      type: "string"
    - variable: "PORTUSVOL"
      label: "Name of the Portusstorage"
      description: "Name for shared storage to use for portus"
      required: true
      type: "string"
    - variable: "DOMAIN"
      label: "Domain"
      description: "Domain of server.  This should be the CN in the certificates and will be the URL to contact the Registry and Web interface"
      required: true
      type: "string"
    - variable: "PPORT"
      label: "Portus port"
      description: "Port on which Portus is accessible from outside"
      required: true
      default: 5000
      type: "int"
services:
  registry:
    scale: 1
    start_on_create: true
  lb:
    start_on_create: true
    lb_config:
      certs: []
      default_cert: wildcard.sdc.t-systems.com
      port_rules:
      - priority: 2
        protocol: https
        service: portusMain
        source_port: 50010
        target_port: 3000
      - priority: 3
        protocol: https
        service: registry
        source_port: 443
        target_port: 5000
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  db:
    scale: 1
    start_on_create: true
  portusMain:
    scale: 1
    start_on_create: true
  PortusBackground:
    scale: 1
    start_on_create: true
